### ISSUE TITLE
How to get the VCF file

### ISSUE THREAD

**Issue by yudizhangzyd** [dcgerard/updog#14]
Hi there,

I was trying to use this tool, but my question is: is your tool a reference free method? If yes, then how to get such VCF files, thanks.

Yudi

**Comment by yudizhangzyd** [comment]
Plus, does it work for just one individual? Thanks.

**Comment by dcgerard** [comment]
Hey @yudizhangzyd, thanks for trying out `updog`!

You need to use some other variant caller to come up with the VCF file. So, you can try out [GATK](https://gatk.broadinstitute.org/hc/en-us), [FreeBayes](https://github.com/freebayes/freebayes), or [TASSEL](https://www.maizegenetics.net/tassel). A reference free approach is written up [here](https://doi.org/10.1371/journal.pgen.1003215). You might find [this](https://bytebucket.org/tasseladmin/tassel-5-source/wiki/docs/TasselPipelineUNEAK.pdf) document helpful.

Best,
David

**Comment by dcgerard** [comment]
For your second question, it works for multiple individuals.

Best,
David

**Comment by yudizhangzyd** [comment]
Thanks David!

**Comment by dcgerard** [comment]
Hey @yudizhangzyd, I've heard folks say not to use UNEAK anymore. But I have seen others use NGSEP, and their paper has some nice references which might be useful: https://doi.org/10.1101/2020.11.28.402131
