### ISSUE TITLE
export_vcf function is not working

### ISSUE THREAD

**Issue by huw143** [dcgerard/updog#28]
Hi friends,

Just let you know that export_vcf function in Updog is not working. 

Before running this function, I loaded the R packages :

library("updog")
library("VariantAnnotation")
library("GenomicRanges")
library("S4Vectors")
library("IRanges")

Then run the export_vcf, 

> export_vcf(obj = mout, filename = "./multidog_fit.vcf")
Error in export_vcf(obj = mout, filename = "./multidog_fit.vcf") : 
  could not find function "export_vcf"

Please see the above for error.

Would you help me fix this issue?

Thanks for developing and maintaining this amazing package, which is really helpful in my research!

Best wishes,

Tiger

**Comment by dcgerard** [comment]
Hey @huw143,

Sorry for the late response, and thanks for trying out `{updog}`!

Right now, `export_vcf()` is not an exported function. You can try it out with `updog:::export_vcf()`, but it's experimental, so I make no guarantees on its correctness. I have a student working on it this semester, trying out corner cases, and so hopefully it will be ready for prime time in the next few months.

Cheers,
David

**Comment by huw143** [comment]
Thank you David for your reply, I really appreciated it. Good to know this, hope everything is going well with your research.

Cheers,

Tiger
